backend:
    name: git-gateway
    branch: main

media_folder: 'public'
public_folder: '/'

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'src/content/blog'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
                - label: 'Image'
                  name: 'image'
                  widget: 'object'
                  fields:
                      - { label: 'Source', name: 'src', widget: 'image' }

    - name: 'projects'
      label: 'Projects'
      folder: 'src/content/projects'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
                - label: 'Image'
                  name: 'image'
                  widget: 'object'
                  fields:
                      - { label: 'Source', name: 'src', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    - name: 'pages'
      label: 'Pages'
      folder: 'src/content/pages'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'SEO'
            name: 'seo'
            widget: 'object'
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Description', name: 'description', widget: 'text' }
                - label: 'Image'
                  name: 'image'
                  widget: 'object'
                  fields:
                      - { label: 'Source', name: 'src', widget: 'image' }
                      - { label: 'Alt Text', name: 'alt', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
